spring:
  application:
    name: user-service
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://mysql:3306/user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    url: jdbc:mysql://mysql:3306
    schemas: user
    user: root
    password: pass
    clean-disabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8000/eureka/
server:
  port: 8001

