spring:
  application:
    name: api-gateway
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8000/eureka/
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
    order:
      path: /order/**
      service: order-servce
