spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

